apiVersion: apps/v1
kind: deployment
  
metadata:
  name: nginx
  labels:
    project: roboshop
    tier: frontend
    component: frontend
spec:
  Replicaset: 3
  selector:
   matchlabels:
      project: roboshop
      tier: frontend
      component: frontend
  template:
   metadata:
   labels:
    project: roboshop
    tier: frontend
    component: frontend
  spec:
   containers:
    - name: nginx
      image: nginx:latest
      ports:
      - container: 80

---
apiVersion: v1  
kind: service
metadata:
  name: nginx
  labels:
    project: roboshop
    tier: frontend
    component: frontend
    purpose: deployment
spec:
  selector:
    matchlabels:
      project: roboshop
      tier: frontend
      component: frontend
      purpose: deployment
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80

          

